---
- name: Installing Nginx
  apt:
    name: nginx
    state: present

- name: Copy application files
  copy:
    src: files/index.html
    dest: /var/www/html/index.html

- name: Copying Nginx config file
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: Reload Nginx

- name: Starting & Enabling Nginx service
  systemd:
    name: nginx
    state: started
    enabled: yes